#!/usr/bin/env bash
# =============================================================================
# Aetherium Nova — Oracle Cloud (Ubuntu 22.04 / Ampere A1) Setup Script
# =============================================================================
# Run as the default OCI user (ubuntu) after first SSH login:
#
#   chmod +x setup-oracle.sh && sudo ./setup-oracle.sh
#
# The script will:
#   1. Update the system
#   2. Install Node.js 22 LTS, Git, Nginx, certbot
#   3. Open ports in iptables (OCI default firewall)
#   4. Clone the repo and build
#   5. Create /etc/aetherium-nova/.env from prompts
#   6. Install and start the systemd service
#   7. Configure Nginx as a reverse proxy (HTTP initially)
# =============================================================================

set -euo pipefail

REPO_URL="https://github.com/ashrafmusa/Aetherium_Nova_v2.git"
APP_DIR="/opt/aetherium-nova"
SERVICE_NAME="aetherium-nova"
APP_USER="aetherium"
ENV_FILE="/etc/aetherium-nova/.env"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
NGINX_CONF="/etc/nginx/sites-available/${SERVICE_NAME}"

# ── Colors ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERR]${NC}  $1"; exit 1; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo ./setup-oracle.sh"

# ── 1. System update ─────────────────────────────────────────────────────────
info "Updating system packages..."
apt-get update -qq && apt-get upgrade -y -qq

# ── 2. Install Node.js 22 via NodeSource ─────────────────────────────────────
info "Installing Node.js 22..."
if ! command -v node &>/dev/null || [[ $(node -v | cut -d. -f1 | tr -d 'v') -lt 22 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y nodejs
fi
info "Node.js $(node -v) | npm $(npm -v)"

# ── 3. Install dependencies ───────────────────────────────────────────────────
info "Installing git, nginx, ufw, certbot..."
apt-get install -y git nginx certbot python3-certbot-nginx ufw unzip jq

# ── 4. Open firewall ports ────────────────────────────────────────────────────
info "Configuring UFW firewall..."
ufw allow OpenSSH
ufw allow 80/tcp    # HTTP / Let's Encrypt
ufw allow 443/tcp   # HTTPS
ufw allow 3001/tcp  # API (restrict after Nginx is up)
ufw allow 6001/tcp  # P2P WebSocket
ufw --force enable
info "UFW status:"
ufw status numbered

# OCI also has kernel iptables rules that drop traffic — open them here
iptables -I INPUT 5 -i ens3 -p tcp --dport 3001 -m state --state NEW,ESTABLISHED -j ACCEPT || true
iptables -I INPUT 5 -i ens3 -p tcp --dport 6001 -m state --state NEW,ESTABLISHED -j ACCEPT || true
# Persist iptables rules
if command -v netfilter-persistent &>/dev/null; then
  netfilter-persistent save
else
  apt-get install -y iptables-persistent -qq
  netfilter-persistent save
fi

# ── 5. Create dedicated user ──────────────────────────────────────────────────
info "Creating app user '${APP_USER}'..."
if ! id "${APP_USER}" &>/dev/null; then
  useradd --system --shell /bin/false --create-home --home-dir "${APP_DIR}" "${APP_USER}"
fi

# ── 6. Clone / update repo ────────────────────────────────────────────────────
info "Cloning repository into ${APP_DIR}..."
if [[ -d "${APP_DIR}/.git" ]]; then
  git -C "${APP_DIR}" pull
else
  git clone "${REPO_URL}" "${APP_DIR}"
fi
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"

# ── 7. Build ──────────────────────────────────────────────────────────────────
info "Installing npm dependencies and building..."
cd "${APP_DIR}"
sudo -u "${APP_USER}" npm ci --omit=dev
# Build needs devDependencies (TypeScript) — install all first then rebuild
npm ci
npm run build
chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}/dist"
info "Build complete."

# ── 8. Write environment file ────────────────────────────────────────────────
mkdir -p /etc/aetherium-nova
chmod 750 /etc/aetherium-nova

if [[ ! -f "${ENV_FILE}" ]]; then
  info "Creating ${ENV_FILE}..."

  echo ""
  echo -e "${YELLOW}>>> Configuration — press Enter to accept defaults ${NC}"
  read -rp "API_KEY (strong secret for REST API): " input_api_key
  API_KEY="${input_api_key:-$(openssl rand -hex 32)}"

  read -rp "MINER_ADDRESS (your validator wallet address, or leave empty): " MINER_ADDRESS
  MINER_ADDRESS="${MINER_ADDRESS:-}"

  read -rp "PEERS (comma-separated ws:// peer URLs, or leave empty): " PEERS
  PEERS="${PEERS:-}"

  cat > "${ENV_FILE}" <<EOF
# Aetherium Nova — Oracle Cloud production environment
# Generated by setup-oracle.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

NODE_ENV=production
PORT=3001
P2P_PORT=6001

# REST API authentication key
API_KEY=${API_KEY}

# Validator address for block reward payouts
MINER_ADDRESS=${MINER_ADDRESS}

# Seed peers  e.g. ws://1.2.3.4:6001,ws://5.6.7.8:6001
PEERS=${PEERS}

# Wallet unlock password (needed for mining/staking CLI commands)
# WALLET_PASSWORD=

# TLS for encrypted P2P (wss://) — set after certbot issues a cert
# P2P_TLS_CERT=/etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem
# P2P_TLS_KEY=/etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem
EOF

  chmod 640 "${ENV_FILE}"
  chown root:"${APP_USER}" "${ENV_FILE}"
  info "Environment file written."
else
  warning "${ENV_FILE} already exists — skipping. Edit manually if needed."
fi

# Print the generated API key so the user can save it
API_KEY_VAL=$(grep '^API_KEY=' "${ENV_FILE}" | cut -d= -f2-)
info "Your API_KEY is: ${API_KEY_VAL}"
info "(Save this — you need it for the explorer and CLI)"

# ── 9. Install systemd service ────────────────────────────────────────────────
info "Installing systemd service..."
cat > "${SERVICE_FILE}" <<UNIT
[Unit]
Description=Aetherium Nova Blockchain Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${APP_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=/usr/bin/node dist/node.js
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}
# Resource limits
LimitNOFILE=65536
MemoryMax=4G

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}"
systemctl start  "${SERVICE_NAME}"
sleep 3
systemctl status "${SERVICE_NAME}" --no-pager || warning "Service may not have started correctly — check: journalctl -u ${SERVICE_NAME} -n 50"

# ── 10. Configure Nginx reverse proxy ─────────────────────────────────────────
info "Configuring Nginx..."
read -rp "Domain name (e.g. node.aetherium-nova.io) or press Enter to skip Nginx: " DOMAIN
if [[ -n "${DOMAIN}" ]]; then
  cat > "${NGINX_CONF}" <<NGINX
# Aetherium Nova — Nginx reverse proxy
# HTTP → redirect to HTTPS (certbot will update this section)
server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://\$host\$request_uri; }
}

# HTTPS reverse proxy to node API
server {
    listen 443 ssl;
    server_name ${DOMAIN};

    # --- TLS (certbot fills these in) ---
    # ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options            DENY                                  always;
    add_header X-Content-Type-Options     nosniff                               always;

    # API pass-through
    location / {
        proxy_pass         http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       \$host;
        proxy_set_header   X-Real-IP  \$remote_addr;
        proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
    }
}
NGINX

  ln -sf "${NGINX_CONF}" /etc/nginx/sites-enabled/
  nginx -t && systemctl reload nginx
  info "Nginx configured for ${DOMAIN}"

  read -rp "Issue a free Let's Encrypt TLS certificate now? [y/N]: " issue_cert
  if [[ "${issue_cert,,}" == "y" ]]; then
    certbot --nginx -d "${DOMAIN}" --non-interactive --agree-tos --email admin@"${DOMAIN}"
    info "TLS certificate issued. HTTPS is live."
  fi
else
  warning "Nginx domain setup skipped. The API is reachable on http://<YOUR_IP>:3001"
fi

# ── 11. Smoke test ────────────────────────────────────────────────────────────
info "Running smoke test..."
sleep 2
STATUS=$(curl -s --max-time 5 -H "x-api-key:${API_KEY_VAL}" http://127.0.0.1:3001/status 2>/dev/null || true)
if [[ -n "${STATUS}" ]]; then
  info "Node is UP: ${STATUS}"
else
  warning "Could not reach node yet. Check: journalctl -u ${SERVICE_NAME} -f"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Aetherium Nova node is deployed on Oracle Cloud!          ${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  API endpoint  : http://$(curl -s ifconfig.me 2>/dev/null || echo '<PUBLIC_IP>'):3001"
echo "  P2P endpoint  : ws://$(curl -s ifconfig.me 2>/dev/null || echo '<PUBLIC_IP>'):6001"
echo "  API_KEY       : ${API_KEY_VAL}"
echo "  Logs          : journalctl -u ${SERVICE_NAME} -f"
echo "  Restart       : systemctl restart ${SERVICE_NAME}"
echo "  Env file      : ${ENV_FILE}"
echo ""
echo "  Next steps:"
echo "    1. Open OCI Security List: TCP ingress 3001 + 6001"
echo "    2. Create/import a miner wallet on the server"
echo "    3. Set MINER_ADDRESS + WALLET_PASSWORD in ${ENV_FILE}"
echo "    4. systemctl restart ${SERVICE_NAME}"
echo "    5. Start mining: WALLET_PASSWORD='...' node dist/cli.js mine"
echo ""
